/**
 * @fileoverview Files a build wrote, which nobody has to read (#126).
 *
 * A 42,860-line `schema.gen.ts` in a real monorepo supplied 1,895 of its package's
 * 1,938 doors and essentially all of its 1,940 types. The hand-written surface — the
 * part somebody could change or break — was about 23 doors in two files. The number was
 * not wrong; every export existed. It was useless, because it described a code
 * generator's output rather than the package, and it made the smallest hand-written
 * package in the monorepo look like far and away the largest.
 *
 * Generated code is the one category this tool can safely say nobody needs to
 * understand: it is derived, it is rewritten on demand, and its own header usually
 * forbids editing it. So it stays on the map and leaves the counts — the same trade
 * made for build-artifact Worker entries in #123, and for the same reason. Hiding a
 * file and declining to count it are different things; only one of them loses
 * information, and somebody looking for a generated type must still find it.
 *
 * Two signals, both conventions rather than guesses.
 */
/**
 * Path shapes that mean "a tool wrote this".
 *
 * Deliberately anchored: `generated/` as a whole path segment, not the substring, so a
 * hand-written `src/generated_reports/summary.ts` is left alone. The protobuf and gRPC
 * spellings are here because they are the same problem in Python and Go, and a repo
 * full of them would otherwise read exactly like the one that prompted this.
 */
const GENERATED_PATH = /(^|\/)(__generated__|_generated|generated)\/|\.gen\.[cm]?[jt]sx?$|\.generated\.[^/]+$|_pb2(_grpc)?\.pyi?$|\.pb\.go$|_pb\.[cm]?[jt]s$|\.g\.dart$/;
/**
 * How far into a file the marker is allowed to be. Generators put it first, but a
 * licence header or a lint directive often gets there before them.
 */
const HEADER_LINES = 5;
/**
 * Header markers, loosest last.
 *
 * `@generated` is the convention Prettier and a lot of JS tooling look for, and Go's
 * `// Code generated … DO NOT EDIT.` is specified exactly by the toolchain. Neither
 * matched the file that prompted this issue, whose first line reads *"This file is
 * generated by the effect-codex-app-server package. Do not edit manually."* — so the
 * third pattern accepts any line that both claims generation and forbids editing.
 * Requiring both halves is what keeps it off a file that merely mentions the word.
 *
 * In either order, because generators disagree about which half to say first. oazapfts
 * writes `DO NOT MODIFY - This file has been generated using oazapfts.`, and the
 * one-directional version of this rule let a 7,702-line OpenAPI client through — 646 of
 * its exports became a package's "ways in" (#173), the exact explosion #126 exists to
 * prevent. The both-halves requirement survives unchanged; the order was an accident.
 */
const GENERATED_HEADER = [
    /@generated\b/,
    /^\s*(\/\/|#|\/\*|\*|--)?\s*Code generated .*DO NOT EDIT\.?/i,
    /\bgenerated\b[^\n]*\bdo not (edit|modify)\b/i,
    /\bdo not (edit|modify)\b[^\n]*\bgenerated\b/i,
];
/** Whether a repo-relative path is one a generator owns. */
export function isGeneratedPath(path) {
    return GENERATED_PATH.test(path.replace(/\\/g, '/'));
}
/** Whether the first few lines of a file say a generator wrote it. */
export function hasGeneratedHeader(text) {
    let from = 0;
    for (let line = 0; line < HEADER_LINES; line++) {
        const end = text.indexOf('\n', from);
        const slice = end === -1 ? text.slice(from) : text.slice(from, end);
        if (GENERATED_HEADER.some((pattern) => pattern.test(slice)))
            return true;
        if (end === -1)
            break;
        from = end + 1;
    }
    return false;
}
/**
 * The whole test, given what a reader of the file already has.
 *
 * `text` is optional because not every caller has read the file — the path alone is
 * enough for the conventions above, and asking for the contents would make this
 * expensive for callers that only hold a filename.
 */
export function isGenerated(path, text) {
    return isGeneratedPath(path) || (text !== undefined && hasGeneratedHeader(text));
}
/**
 * Stamps every generated file, and everything declared inside one, in place.
 *
 * Central and language-neutral for the same reason the boundary merge is: three tiers
 * create file nodes in six places, and a rule about what a *file* is has no business
 * being restated in each of them. Runs beside `markRetiredFiles`, which does the same
 * job for code that says it is dead — and, like it, marks rather than drops.
 *
 * `readHeader` is how the header patterns get to run at all. They sat here fully
 * written and called by nothing (#173) — no caller ever passed text in — which is how a
 * 7,702-line oazapfts client whose fourth line says "DO NOT MODIFY - This file has been
 * generated" put 646 export doors on a package. The path rules stay first because they
 * are free; the header is read only for files they did not already settle.
 */
export function markGeneratedFiles(nodes, readHeader) {
    const paths = new Set();
    for (const node of nodes) {
        if (node.kind !== 'file' || !node.path)
            continue;
        if (!isGeneratedPath(node.path)) {
            const head = readHeader?.(node.path);
            if (!head || !hasGeneratedHeader(head))
                continue;
        }
        node.meta.generated = true;
        paths.add(node.path);
    }
    // The functions and types too, so a rule can ask the node in front of it rather than
    // having to find its file first. Every count this feeds is over those, not over files.
    if (paths.size > 0) {
        for (const node of nodes) {
            if (node.kind === 'file' || !node.path)
                continue;
            if (paths.has(node.path))
                node.meta.generated = true;
        }
    }
    return { files: paths.size };
}
/** Whether a node was stamped by the pass above. */
export function isGeneratedNode(node) {
    return Boolean(node.meta?.generated);
}
//# sourceMappingURL=generated.js.map