/**
 * @fileoverview Code a generator wrote, which nobody has to read (#126).
 *
 * A real package reported `17 files · 1938 ways in`. 1,895 of those came from one
 * 42,860-line `schema.gen.ts`; the surface its authors had actually committed to was
 * about 23 names in two files. Nothing about the number was false — every export
 * existed — but it described a code generator's output rather than the package, and it
 * made the smallest hand-written package in the monorepo look like the largest thing in
 * the repo. The same file dragged docstring coverage to 0%.
 *
 * The rule these pin is the one #123 settled for build-artifact Worker entries: a build
 * wrote it, so it is not something a person has to account for — and it is *set aside*,
 * never hidden. A reader who goes looking for a generated type still has to find it.
 */
import assert from 'node:assert/strict';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { analyzeProject } from '../dist/node/index.js';
import { hasGeneratedHeader, isGeneratedPath } from '../dist/node/analyze/generated.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const { atlas } = await analyzeProject(path.join(here, 'fixtures', 'generated'), {
  followReferences: true,
  cache: 'off',
});

const file = (p) => atlas.nodes.find((n) => n.kind === 'file' && n.path === p);
const doors = atlas.nodes.filter((n) => n.kind === 'endpoint' && n.meta.endpointKind === 'export');

test('a generated file is marked, and the files beside it are not', () => {
  assert.equal(file('src/_generated/schema.gen.ts').meta.generated, true);
  assert.equal(file('src/legacy_pb2.py')?.meta.generated, true, 'protobuf output, in Python spelling');
  assert.equal(file('src/index.ts').meta.generated ?? false, false);
});

test('what a generator emits is not a commitment anybody made', () => {
  const names = doors.map((d) => d.name).sort();
  // `connect` and `Options` are the whole hand-written surface. GenA/GenB/GenC and
  // genOne/genTwo are five more exports in the same project, and none of them is a
  // promise: semver does not bind what the generator will rewrite tomorrow.
  assert.deepEqual(names, ['Options', 'connect']);
  assert.equal(
    doors.some((d) => (d.meta.sites?.[0]?.path ?? '').includes('_generated')),
    false,
  );
});

test('the file is still on the map, because setting aside is not hiding', () => {
  // The alternative — dropping it — would mean a reader who went looking for a
  // generated type found nothing and could not tell whether it existed.
  assert.ok(file('src/_generated/schema.gen.ts'), 'the file is present');
  assert.ok(
    atlas.nodes.some((n) => n.kind === 'type' && n.name === 'GenA'),
    'and so is what it declares',
  );
});

test('nobody is scored on documenting a file a generator rewrites', () => {
  const stats = atlas.meta.stats;
  assert.equal(stats.generatedFiles, 2, 'the .gen.ts and the _pb2.py');
  assert.ok(stats.files > stats.generatedFiles, 'they are still counted among the files');
});

// ---------------------------------------------------------------------------
// The two signals, on their own

test('the path conventions are anchored, not substrings', () => {
  assert.equal(isGeneratedPath('src/_generated/schema.gen.ts'), true);
  assert.equal(isGeneratedPath('src/__generated__/types.ts'), true);
  assert.equal(isGeneratedPath('api/generated/client.ts'), true);
  assert.equal(isGeneratedPath('proto/thing_pb2.py'), true);
  assert.equal(isGeneratedPath('proto/thing.pb.go'), true);
  assert.equal(isGeneratedPath('src/schema.gen.ts'), true);

  // The ones a looser rule would have taken with it. Somebody's hand-written reporting
  // module is not a generator's output because the word appears in its name.
  assert.equal(isGeneratedPath('src/generated_reports/summary.ts'), false);
  assert.equal(isGeneratedPath('src/degenerate.ts'), false);
  assert.equal(isGeneratedPath('src/gen.ts'), false);
});

test('a header has to claim generation *and* forbid editing', () => {
  assert.equal(hasGeneratedHeader('// @generated by protoc\nexport const a = 1;'), true);
  assert.equal(hasGeneratedHeader('// Code generated by protoc-gen-go. DO NOT EDIT.\n'), true);
  // The spelling that prompted the issue, which matched neither published convention.
  assert.equal(hasGeneratedHeader('// This file is generated by the x package. Do not edit manually.\n'), true);
  // Half a claim is not a claim: plenty of hand-written files discuss generating things.
  assert.equal(hasGeneratedHeader('// This module has generated reports since 2019.\n'), false);
  assert.equal(hasGeneratedHeader('// Do not edit this without asking Priya first.\n'), false);
  // And it has to be near the top, or every file that mentions it in passing qualifies.
  assert.equal(hasGeneratedHeader('a\nb\nc\nd\ne\nf\n// @generated\n'), false);
});
