/**
 * @fileoverview The commit an atlas was written at, and the warning when the code moves on.
 *
 * `generatedAt` says when the analyzer ran. It does not say whether what it found is
 * still true, and the difference between those two is the whole feature: an atlas from
 * last week is perfect if nobody committed since, and one from four minutes ago is
 * describing deleted code if an agent has been working. Only a commit can tell them
 * apart.
 *
 * Which makes the failure directions asymmetric, and that is what most of this file
 * defends. A false alarm costs somebody a re-analysis. A false all-clear costs an agent
 * acting confidently on a map of code that no longer exists — so every case where the
 * commit cannot be established has to produce silence rather than reassurance, and the
 * word "stale" must never appear as `false` on an answer where nobody could actually
 * check.
 *
 * The reader is exercised against real repositories rather than hand-built directories,
 * because the shapes that break it are git's own: a linked worktree keeps its HEAD in one
 * place and its branches in another, a packed ref and a loose ref can both exist for the
 * same branch, and only one of them is current.
 */
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { analyzeProject, AtlasSource, callMcpTool, persistAtlas } from '../dist/node/index.js';
// Not part of the public surface: it answers one question for two callers inside the
// tool, and widening `index.ts` to reach it from here would be the tail wagging the dog.
import { headCommit, shortCommit } from '../dist/node/util/head.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'app-atlas-stale-'));

test.after(() => fs.rmSync(workspace, { recursive: true, force: true }));

/** Runs git in `cwd`, failing the test loudly rather than leaving a puzzling null later. */
function git(cwd, ...args) {
  return execFileSync('git', args, {
    cwd,
    encoding: 'utf8',
    // A contributor's own `user.name`, `commit.gpgsign` or `init.defaultBranch` must not
    // decide whether this suite passes.
    env: {
      ...process.env,
      GIT_CONFIG_GLOBAL: path.join(workspace, 'nonexistent-gitconfig'),
      GIT_CONFIG_SYSTEM: path.join(workspace, 'nonexistent-gitconfig'),
      GIT_AUTHOR_NAME: 'Test',
      GIT_AUTHOR_EMAIL: 'test@example.com',
      GIT_COMMITTER_NAME: 'Test',
      GIT_COMMITTER_EMAIL: 'test@example.com',
    },
  }).trim();
}

/** A real repository with one commit in it, copied from a fixture so it has code to read. */
function repo(name, fixture = 'exposure') {
  const dir = path.resolve(fs.mkdtempSync(path.join(workspace, `${name}-`)));
  fs.cpSync(path.join(here, 'fixtures', fixture), dir, { recursive: true });
  git(dir, 'init', '--quiet');
  // What the CLI writes for real, and what keeps the later commits here about code:
  // an atlas committed alongside the tree it describes would move HEAD every time one
  // was written, which is a staleness warning generated by the test's own bookkeeping.
  fs.writeFileSync(path.join(dir, '.gitignore'), '.app-atlas/\n');
  git(dir, 'add', '-A');
  git(dir, 'commit', '--quiet', '-m', 'first');
  return dir;
}

/** One more commit, so the working tree moves without the analysis being re-run. */
function commitSomething(dir, message = 'second') {
  fs.writeFileSync(path.join(dir, `note-${message}.txt`), message);
  git(dir, 'add', '-A');
  git(dir, 'commit', '--quiet', '-m', message);
  return git(dir, 'rev-parse', 'HEAD');
}

const analyze = (dir) => analyzeProject(dir, { followReferences: true, cache: 'off' });

/**
 * Writes the atlas where `app-atlas analyze` writes it: inside the project it describes.
 *
 * Other suites persist into a throwaway directory to keep `.app-atlas` out of a checked-in
 * fixture, and that is the right trade there. It is the wrong one here, because the thing
 * under test is the relationship between an atlas and the working tree it belongs to, and
 * separating them tests a configuration that never occurs. These projects are disposable
 * clones in a temp directory, so there is nothing to keep clean.
 */
function serveFrom(dir, atlas) {
  persistAtlas(dir, atlas);
  return dir;
}

const call = (dir, name, args = {}) => callMcpTool(new AtlasSource(dir), name, args);
const textOf = (result) => result.content.map((block) => block.text).join('\n');

// ---------------------------------------------------------------------------
// Reading the commit
// ---------------------------------------------------------------------------

test('the commit a working tree is on is the one git reports', () => {
  const dir = repo('plain');
  assert.equal(headCommit(dir), git(dir, 'rev-parse', 'HEAD'));
});

test('…and it is found from a subdirectory, the way git resolves a repository', () => {
  const dir = repo('plain-sub');
  const sub = path.join(dir, 'src');
  assert.ok(fs.existsSync(sub), 'fixture should have a src/ to look up from');
  assert.equal(headCommit(sub), git(dir, 'rev-parse', 'HEAD'));
});

test('…and a directory under no repository at all reports nothing rather than guessing', () => {
  const bare = fs.mkdtempSync(path.join(workspace, 'norepo-'));
  assert.equal(headCommit(bare), null);
  assert.equal(headCommit(path.join(bare, 'does', 'not', 'exist')), null);
});

test('…and a repository with no commit yet reports nothing, not an empty string', () => {
  const dir = fs.mkdtempSync(path.join(workspace, 'unborn-'));
  git(dir, 'init', '--quiet');
  assert.equal(headCommit(dir), null);
});

test('a detached HEAD reads the commit it is detached at', () => {
  const dir = repo('detached');
  const first = git(dir, 'rev-parse', 'HEAD');
  commitSomething(dir);
  git(dir, 'checkout', '--quiet', first);
  assert.equal(headCommit(dir), first);
});

test('a linked worktree reads its own HEAD, not the checkout it was made from', () => {
  const dir = repo('worktrees');
  const main = git(dir, 'rev-parse', 'HEAD');
  const linked = path.join(workspace, 'linked-tree');

  git(dir, 'worktree', 'add', '--quiet', '-b', 'side', linked);
  fs.writeFileSync(path.join(linked, 'only-here.txt'), 'side');
  git(linked, 'add', '-A');
  git(linked, 'commit', '--quiet', '-m', 'on the side branch');

  const side = git(linked, 'rev-parse', 'HEAD');
  assert.notEqual(side, main, 'the two trees should be on different commits');
  // The failure this guards is subtle: `.git` here is a file, HEAD lives in the linked
  // worktree's own directory, and `refs/heads/side` lives back in the main repository.
  // Reading either half alone gives the other tree's commit, or none.
  assert.equal(headCommit(linked), side);
  assert.equal(headCommit(dir), main);
});

test('a branch that has been packed away is still read, and a loose ref still wins', () => {
  const dir = repo('packed');
  const packed = commitSomething(dir, 'before-gc');
  git(dir, 'pack-refs', '--all');
  assert.ok(!fs.existsSync(path.join(dir, '.git', 'refs', 'heads', git(dir, 'branch', '--show-current'))));
  assert.equal(headCommit(dir), packed, 'packed-refs is the only place the branch is now');

  // A commit after the pack writes a loose ref again while the stale packed line stays.
  // Reading the packed table first would answer with the commit before last.
  const loose = commitSomething(dir, 'after-gc');
  assert.equal(headCommit(dir), loose);
});

test('the short form is what a person reads, and the atlas keeps the whole name', () => {
  const dir = repo('short');
  const full = headCommit(dir);
  assert.match(full, /^[0-9a-f]{40}$/);
  assert.equal(shortCommit(full), full.slice(0, 7));
});

// ---------------------------------------------------------------------------
// What the analyzer records
// ---------------------------------------------------------------------------

test('an analysis records the commit it read', async () => {
  const dir = repo('records');
  const { atlas } = await analyze(dir);
  assert.equal(atlas.meta.vcs?.commit, git(dir, 'rev-parse', 'HEAD'));
});

test('…and a project under no version control records nothing rather than a blank commit', async () => {
  const dir = path.resolve(fs.mkdtempSync(path.join(workspace, 'vcsless-')));
  fs.cpSync(path.join(here, 'fixtures', 'exposure'), dir, { recursive: true });

  const { atlas } = await analyze(dir);
  // Absent, not `{ commit: '' }`. Everything downstream reads the absence as "nobody
  // could tell", and a falsy commit that is nonetheless present would be compared.
  assert.equal(atlas.meta.vcs, undefined);
  assert.ok(!('vcs' in atlas.meta), 'the key itself should not be written');
});

// ---------------------------------------------------------------------------
// What the agent is told
// ---------------------------------------------------------------------------

test('an atlas that matches the working tree says nothing about staleness', async () => {
  const dir = repo('fresh');
  const { atlas } = await analyze(dir);
  const served = serveFrom(dir, atlas);

  const result = call(served, 'list_doors');
  const text = textOf(result);
  assert.ok(!/moved since/i.test(text), `expected no staleness warning, got:\n${text}`);
  assert.equal(result.structuredContent.stale, false);
  assert.equal(result.structuredContent.analyzedCommit, git(dir, 'rev-parse', 'HEAD'));
  assert.equal(result.structuredContent.currentCommit, git(dir, 'rev-parse', 'HEAD'));
});

test('an atlas from before the last commit says so, in both halves of the answer', async () => {
  const dir = repo('moved');
  const { atlas } = await analyze(dir);
  const analyzedAt = git(dir, 'rev-parse', 'HEAD');
  const served = serveFrom(dir, atlas);

  const now = commitSomething(dir);
  const result = call(served, 'list_doors');
  const text = textOf(result);

  assert.match(text, /moved since it was analysed/i);
  assert.ok(text.includes(shortCommit(analyzedAt)), 'the warning should name the commit analysed');
  assert.ok(text.includes(shortCommit(now)), 'the warning should name the commit checked out now');
  assert.match(text, /app-atlas analyze/, 'and say how to fix it');
  // The check reads commits, so it cannot see edits nobody has committed. An agent told
  // the atlas matches HEAD would otherwise read that as matching the files on disk.
  assert.match(text, /uncommitted edits/i);

  assert.equal(result.structuredContent.stale, true);
  assert.equal(result.structuredContent.analyzedCommit, analyzedAt);
  assert.equal(result.structuredContent.currentCommit, now);
});

test('…and it says it on every tool, because an agent reads the answer in front of it', async () => {
  const dir = repo('every-tool');
  const { atlas } = await analyze(dir);
  const served = serveFrom(dir, atlas);
  commitSomething(dir);

  // Not a sample: the warning is worth nothing if it depends on which question was asked.
  for (const tool of ['unguarded_doors', 'list_doors', 'unimported_files', 'data_stores', 'env_vars']) {
    const result = call(served, tool);
    assert.match(textOf(result), /moved since it was analysed/i, `${tool} should carry the warning`);
    assert.equal(result.structuredContent.stale, true, `${tool} should carry the flag`);
  }
});

test('a project with no version control claims nothing either way', async () => {
  const dir = path.resolve(fs.mkdtempSync(path.join(workspace, 'quiet-')));
  fs.cpSync(path.join(here, 'fixtures', 'exposure'), dir, { recursive: true });
  const { atlas } = await analyze(dir);
  const served = serveFrom(dir, atlas);

  const result = call(served, 'list_doors');
  assert.ok(!/moved since/i.test(textOf(result)));
  // The absence is the point. `stale: false` here would be an all-clear nobody checked,
  // and it is the one thing this feature must never say.
  assert.ok(!('stale' in result.structuredContent), 'no verdict without both commits');
  assert.ok(!('analyzedCommit' in result.structuredContent));
  assert.ok(!('currentCommit' in result.structuredContent));
});

test('an atlas written before this existed is served without a verdict, not as fresh', async () => {
  const dir = repo('legacy');
  const { atlas } = await analyze(dir);
  // Exactly what an atlas from an older App Atlas looks like on disk.
  delete atlas.meta.vcs;
  const served = serveFrom(dir, atlas);
  commitSomething(dir);

  const result = call(served, 'list_doors');
  assert.ok(!/moved since/i.test(textOf(result)), 'nothing to compare against, so nothing is claimed');
  assert.ok(!('stale' in result.structuredContent));
  // The timestamp is still there, and is still the honest claim.
  assert.equal(result.structuredContent.analyzedAt, atlas.meta.generatedAt);
});

test('the warning follows the tree, so a re-analysis clears it', async () => {
  const dir = repo('cleared');
  const first = await analyze(dir);
  const served = serveFrom(dir, first.atlas);
  commitSomething(dir);
  assert.match(textOf(call(served, 'list_doors')), /moved since it was analysed/i);

  const second = await analyze(dir);
  persistAtlas(served, second.atlas);
  const result = call(served, 'list_doors');
  assert.ok(!/moved since/i.test(textOf(result)), 'a fresh analysis should end the warning');
  assert.equal(result.structuredContent.stale, false);
});
