/**
 * @fileoverview Files a build wrote, which nobody has to read (#126).
 *
 * A 42,860-line `schema.gen.ts` in a real monorepo supplied 1,895 of its package's
 * 1,938 doors and essentially all of its 1,940 types. The hand-written surface — the
 * part somebody could change or break — was about 23 doors in two files. The number was
 * not wrong; every export existed. It was useless, because it described a code
 * generator's output rather than the package, and it made the smallest hand-written
 * package in the monorepo look like far and away the largest.
 *
 * Generated code is the one category this tool can safely say nobody needs to
 * understand: it is derived, it is rewritten on demand, and its own header usually
 * forbids editing it. So it stays on the map and leaves the counts — the same trade
 * made for build-artifact Worker entries in #123, and for the same reason. Hiding a
 * file and declining to count it are different things; only one of them loses
 * information, and somebody looking for a generated type must still find it.
 *
 * Two signals, both conventions rather than guesses.
 */

/**
 * Path shapes that mean "a tool wrote this".
 *
 * Deliberately anchored: `generated/` as a whole path segment, not the substring, so a
 * hand-written `src/generated_reports/summary.ts` is left alone. The protobuf and gRPC
 * spellings are here because they are the same problem in Python and Go, and a repo
 * full of them would otherwise read exactly like the one that prompted this.
 */
const GENERATED_PATH =
  /(^|\/)(__generated__|_generated|generated)\/|\.gen\.[cm]?[jt]sx?$|\.generated\.[^/]+$|_pb2(_grpc)?\.pyi?$|\.pb\.go$|_pb\.[cm]?[jt]s$|\.g\.dart$/;

/**
 * How far into a file the marker is allowed to be. Generators put it first, but a
 * licence header or a lint directive often gets there before them.
 */
const HEADER_LINES = 5;

/**
 * Header markers, loosest last.
 *
 * `@generated` is the convention Prettier and a lot of JS tooling look for, and Go's
 * `// Code generated … DO NOT EDIT.` is specified exactly by the toolchain. Neither
 * matched the file that prompted this issue, whose first line reads *"This file is
 * generated by the effect-codex-app-server package. Do not edit manually."* — so the
 * third pattern accepts any line that both claims generation and forbids editing.
 * Requiring both halves is what keeps it off a file that merely mentions the word.
 */
const GENERATED_HEADER = [
  /@generated\b/,
  /^\s*(\/\/|#|\/\*|\*|--)?\s*Code generated .*DO NOT EDIT\.?/i,
  /\bgenerated\b[^\n]*\bdo not (edit|modify)\b/i,
];

/** Whether a repo-relative path is one a generator owns. */
export function isGeneratedPath(path: string): boolean {
  return GENERATED_PATH.test(path.replace(/\\/g, '/'));
}

/** Whether the first few lines of a file say a generator wrote it. */
export function hasGeneratedHeader(text: string): boolean {
  let from = 0;
  for (let line = 0; line < HEADER_LINES; line++) {
    const end = text.indexOf('\n', from);
    const slice = end === -1 ? text.slice(from) : text.slice(from, end);
    if (GENERATED_HEADER.some((pattern) => pattern.test(slice))) return true;
    if (end === -1) break;
    from = end + 1;
  }
  return false;
}

/**
 * The whole test, given what a reader of the file already has.
 *
 * `text` is optional because not every caller has read the file — the path alone is
 * enough for the conventions above, and asking for the contents would make this
 * expensive for callers that only hold a filename.
 */
export function isGenerated(path: string, text?: string): boolean {
  return isGeneratedPath(path) || (text !== undefined && hasGeneratedHeader(text));
}

/**
 * Stamps every generated file, and everything declared inside one, in place.
 *
 * Central and language-neutral for the same reason the boundary merge is: three tiers
 * create file nodes in six places, and a rule about what a *file* is has no business
 * being restated in each of them. Runs beside `markRetiredFiles`, which does the same
 * job for code that says it is dead — and, like it, marks rather than drops.
 */
export function markGeneratedFiles(nodes: { kind: string; path: string | null; meta: Record<string, unknown> }[]): {
  files: number;
} {
  const paths = new Set<string>();
  for (const node of nodes) {
    if (node.kind !== 'file' || !node.path) continue;
    if (!isGeneratedPath(node.path)) continue;
    node.meta.generated = true;
    paths.add(node.path);
  }
  // The functions and types too, so a rule can ask the node in front of it rather than
  // having to find its file first. Every count this feeds is over those, not over files.
  if (paths.size > 0) {
    for (const node of nodes) {
      if (node.kind === 'file' || !node.path) continue;
      if (paths.has(node.path)) node.meta.generated = true;
    }
  }
  return { files: paths.size };
}

/** Whether a node was stamped by the pass above. */
export function isGeneratedNode(node: { meta?: Record<string, unknown> }): boolean {
  return Boolean(node.meta?.generated);
}
