/**
 * @fileoverview Whether a file App Atlas is about to write is one other people will read.
 *
 * A file under version control has a different audience from one sitting in somebody's
 * working directory: it is regenerated by different people on different machines, and
 * whatever it says has to be true for all of them. That difference decides what may go
 * into `ATLAS.md` (issue #69), and the only way to know it is to ask git.
 */
import { spawnSync } from 'node:child_process';
import path from 'node:path';

/**
 * True when git is tracking this exact path — not merely that it sits inside a repo.
 *
 * Tracked is the question worth asking, rather than "is there a `.git` above this",
 * because almost every project this tool runs on is a git repo and only some of them
 * commit their map. The moment somebody commits it, it becomes a shared artifact and
 * this starts answering yes, which is exactly when the answer should change.
 *
 * Never throws. Any failure — git not installed, not a repository, a path outside the
 * work tree, a hung binary — is reported as untracked, which keeps the map's own
 * behaviour the same on a machine with no git as it is in a directory nobody shares.
 */
export function isTrackedByGit(filePath: string): boolean {
  try {
    const result = spawnSync('git', ['ls-files', '--error-unmatch', '--', path.basename(filePath)], {
      cwd: path.dirname(filePath),
      stdio: 'ignore',
      timeout: 5_000,
      // Git is a program name, and the arguments below are never a shell's business:
      // a repository path can contain a space, a quote or a semicolon.
      shell: false,
    });
    return result.status === 0;
  } catch {
    return false;
  }
}
