/**
 * @fileoverview ATLAS.md — the atlas, written for the agent that wrote the app.
 *
 * SPEC.md section 7. An agent starting a session in an unfamiliar repository spends
 * its first several thousand tokens rediscovering the shape of the thing; aider's
 * repo-map proved that handing it the map instead is worth real accuracy. This is that
 * map, in the cheapest form that survives being pasted into a context window.
 *
 * Three rules keep it useful:
 *
 *   - **Facts before prose.** Counts, routes, tables and paths — the things an agent
 *     can act on — come first, and every one of them is compiler-derived.
 *   - **Say what is generated.** A sentence a model wrote is marked `(ai)`. An agent
 *     reading this should weigh its own species' output accordingly.
 *   - **Bounded.** Every list is capped. A map that does not fit in a context window
 *     is not a map, and the atlas itself is one command away for anything deeper.
 */
import type { AtlasGraph } from '../model/graph.js';
import { describeChanges } from '../model/changes.js';
import type { AtlasChanges, DoorChange } from '../model/types.js';
import { authHeadline } from '../model/exposure.js';
import { buildInsights } from '../model/insights.js';
import type { RouteInsight } from '../model/insights.js';
import { grammarTier } from '../model/tiers.js';
import type { UnimportedView } from '../model/unimported.js';
import { buildTypeView } from '../model/typeview.js';
import { findPersonalData } from '../model/personal.js';
import type { SummarySource } from '../model/types.js';

const MAX_ROUTES = 40;
const MAX_PARTS = 14;
const MAX_TYPES = 24;
const MAX_START_FILES = 8;
const MAX_ENV = 30;
const MAX_CHANGED_DOORS = 20;
/** Enough for a reader to see the shape of the access; the boundary table has them all. */
const MAX_REACHING_DOORS = 6;
/** Long enough for a real schema, short enough that the section is still read. */
const MAX_PERSONAL_TABLES = 12;

/** Doors nobody outside can knock on, so they never appear in the auth table. */
const OTHER_DOORS = new Set(['webhook', 'cron', 'queue', 'cli', 'file-read']);

const MAX_PORTS = 20;

export interface MarkdownOptions {
  /** Stamped into the header so a stale copy is obvious. Defaults to the atlas's own. */
  generatedAt?: string;
  toolVersion?: string;
  /**
   * This file is committed, so it is read by people who did not run it (issue #69).
   *
   * Passed in rather than worked out here, because the renderer is handed a graph and
   * should not be asking the filesystem questions — and because the caller is the only
   * one that knows where the text is going. Left off, everything is written as though
   * for the person who ran the command, which is the right default for `--stdout` and
   * for a map nobody shares.
   */
  shared?: boolean;
}

export function renderAtlasMarkdown(graph: AtlasGraph, options: MarkdownOptions = {}): string {
  const meta = graph.meta;
  const stats = meta.stats;
  const insights = buildInsights(graph);
  const overview = graph.getOverview();
  const out: string[] = [];

  // The header is where this document says how much its own facts are worth, so it has
  // to change when the answer does. "Each language's own parser and type checker" stopped
  // being true the day a tree-sitter grammar could answer for a language, and a map whose
  // first line overstates its evidence has no business badging anybody's routes.
  const tier = grammarTier(graph.allNodes());
  out.push(`# ${meta.name} — map`);
  out.push('');
  out.push(
    `> Generated by App Atlas v${options.toolVersion ?? meta.toolVersion} on ${
      (options.generatedAt ?? meta.generatedAt).slice(0, 10)
    }. Facts are derived by each language's own parser${tier ? '' : ' and type checker'}; sentences marked \`(ai)\` were generated and may be wrong. Re-run \`app-atlas export\` after the code changes.`,
  );
  if (tier) {
    out.push('>');
    out.push(`> ${tier.sentence}`);
  }
  out.push('');

  const app = overview.app;
  if (app?.summary) {
    out.push(`${app.summary}${mark(app.summarySource)}`);
    out.push('');
  }

  // --- what changed ---
  // First, because an agent handed this map at the start of a session is most often
  // being asked to carry on from where the last one stopped, and because the reader who
  // is not an agent came here asking what the weekend did to their app.
  appendChanges(out, meta.changes, Boolean(options.shared));

  // --- numbers ---
  out.push('## By the numbers');
  out.push('');
  out.push(
    `- ${n(stats.files)} files · ${n(stats.linesOfCode)} lines · ${n(stats.modules)} folders · ${n(stats.functions)} functions · ${n(stats.types)} types`,
  );
  out.push(
    `- ${n(stats.endpoints)} ways in · ${n(stats.externalServices)} outside ${plural(stats.externalServices, 'service')} · ${n(stats.stores)} data ${plural(stats.stores, 'store')} · ${n(stats.envVars)} env vars`,
  );
  if (meta.frameworks.length > 0) out.push(`- Built with ${meta.frameworks.join(', ')}`);
  out.push(
    `- ${percent(stats.documentedFiles, stats.files)} of files carry a docstring App Atlas reads verbatim${
      stats.staleDocs > 0 ? ` · ${stats.staleDocs} describe code that has since changed` : ''
    }`,
  );
  // An agent reading this file needs the caveat before the numbers it qualifies, not in
  // a footnote. Every count above is a lower bound when a file went unread, and the
  // sections below can be missing whole routes rather than merely describing them badly.
  if (stats.unreadFiles > 0) {
    out.push(
      `- **App Atlas could not read ${n(stats.unreadFiles)} ${plural(stats.unreadFiles, 'file')}**, so whatever ` +
        'they declare — a route, a check, a table — is missing from everything below',
    );
  }
  out.push('');

  // --- ways in ---
  if (insights.auth.routes.length > 0) {
    out.push('## Ways in');
    out.push('');
    const auth = authHeadline(stats);
    if (auth) {
      out.push(auth.tone === 'warn' ? `**${sentenceCase(auth.headline)}.** They are listed first.` : `${sentenceCase(auth.headline)}.`);
      for (const caveat of auth.caveats) out.push(`- ${sentenceCase(caveat)}.`);
      out.push('');
    }
    out.push('| Kind | Route | Auth | Writes | Where |');
    out.push('|---|---|---|---|---|');
    for (const route of insights.auth.routes.slice(0, MAX_ROUTES)) {
      out.push(
        `| ${route.method ?? route.endpointKind} | ${route.route ?? route.name} | ${authCell(route)} | ${route.writes ? 'yes' : '—'} | ${route.sites[0]?.path ?? '—'} |`,
      );
    }
    if (insights.auth.routes.length > MAX_ROUTES) {
      out.push(`| … | ${insights.auth.routes.length - MAX_ROUTES} more | | | |`);
    }
    out.push('');
  }

  // Ports come before the crons and workers below, and are deliberately not filed with
  // them: that section exists for doors a stranger *cannot* knock on, and a port
  // published on every interface is the most knockable thing in the repo. Folding these
  // in would have put a published database under a heading saying nobody can reach it.
  appendPorts(out, graph);

  // Webhooks, crons and workers are not measured for auth coverage — a stranger cannot
  // knock on them — but an agent about to change this code still needs to know they run.
  const others = graph
    .nodesOfKind('endpoint')
    .filter((node) => OTHER_DOORS.has(String((node.meta as { endpointKind?: string }).endpointKind)));
  if (others.length > 0) {
    out.push('## Also runs on its own');
    out.push('');
    for (const node of others) {
      const meta = node.meta as { endpointKind?: string; route?: string; schedule?: string; sites?: { path: string }[] };
      const when = meta.schedule ? ` (${meta.schedule})` : '';
      out.push(`- **${meta.endpointKind}** ${meta.route ?? node.name}${when} — \`${meta.sites?.[0]?.path ?? '—'}\``);
    }
    out.push('');
  }

  // --- where data goes ---
  if (insights.stores.length + insights.services.length > 0) {
    out.push('## Where data goes');
    out.push('');
    for (const store of insights.stores) {
      const tables = store.tables.length > 0 ? ` — tables: ${store.tables.join(', ')}` : '';
      out.push(`- **${store.name}** (${store.client}) — ${store.reads} reads, ${store.writes} writes${tables}`);
    }
    for (const service of insights.services) {
      out.push(
        `- **${service.name}** (${service.category}) — ${service.callSites} call ${service.callSites === 1 ? 'site' : 'sites'}${
          service.evidence.length > 0 ? ` via ${service.evidence.slice(0, 2).join(', ')}` : ''
        }`,
      );
    }
    out.push('');
  }

  // --- the parts ---
  const parts = overview.topLevel.filter((node) => node.kind === 'module').slice(0, MAX_PARTS);
  if (parts.length > 0) {
    out.push('## The parts');
    out.push('');
    for (const part of parts) {
      const files = Number(part.meta.descendantFileCount ?? part.childCount);
      const summary = part.summary ? ` — ${oneLine(part.summary)}${mark(part.summarySource)}` : '';
      out.push(`- \`${part.path || part.name}\` (${files} ${plural(files, 'file')}, ${part.zone})${summary}`);
    }
    out.push('');
  }

  // --- what nothing points at ---
  // Beside "the parts" rather than beside the reading order at the bottom, because it
  // answers the same question those do — what is this made of — and because an agent
  // about to change this code needs it before it starts, not after.
  appendUnimported(out, overview.unimported);

  // --- shapes ---
  const types = buildTypeView(graph, MAX_TYPES);
  const tables = types.cards.filter((card) => card.typeKind === 'table');
  const shapes = types.cards.filter((card) => card.typeKind !== 'table');

  if (tables.length > 0) {
    out.push('## Database tables');
    out.push('');
    for (const table of tables) {
      // A table found only by name in a query has no columns to list. Say so, rather
      // than trailing off after the dash as though the row were still being written.
      const columns = table.fields.map((field) => `${field.name}: ${field.type}`).join(', ');
      out.push(`- **${table.name}** — ${columns || 'columns unknown'}`);
    }
    out.push('');
  }

  appendPersonalData(out, graph);

  if (shapes.length > 0) {
    out.push('## Key types');
    out.push('');
    for (const card of shapes) {
      const shape =
        card.fields.length > 0
          ? card.fields.map((field) => `${field.name}${field.optional ? '?' : ''}`).join(', ')
          : (card.aliasOf ?? '');
      out.push(
        `- **${card.name}** (${card.typeKind}, \`${card.path}\`)${card.usage > 0 ? ` — used in ${card.usage} places` : ''}${shape ? ` — ${shape}` : ''}`,
      );
    }
    if (types.total > types.cards.length) {
      out.push(`- …and ${types.total - types.cards.length} more types.`);
    }
    out.push('');
  }

  // --- env ---
  if (insights.env.total > 0) {
    out.push('## Environment variables');
    out.push('');
    // The star has to mean exactly what the footnote below says it means. It used to be
    // `!documented`, while the count underneath excluded platform variables — so
    // nextjs-subscription-payments printed three stars above the words "2 of 10", and a
    // reader who counted them found the tool disagreeing with itself on the same screen.
    // `NEXT_PUBLIC_VERCEL_URL` is set by the host; nobody forgot to write it down.
    const names = insights.env.vars.slice(0, MAX_ENV).map((v) => {
      const mark = v.platform ? '†' : v.documented ? '' : '*';
      return `\`${v.name}\`${mark}`;
    });
    out.push(names.join(', ') + (insights.env.total > MAX_ENV ? `, …${insights.env.total - MAX_ENV} more` : ''));
    if (insights.env.undocumented.length > 0) {
      out.push('');
      out.push(
        `\\* not in ${insights.env.exampleFile ?? '.env.example'} — ${insights.env.undocumented.length} of ${insights.env.total} are read by the code but written down nowhere.`,
      );
    }
    if (insights.env.vars.slice(0, MAX_ENV).some((v) => v.platform)) {
      out.push('');
      out.push('† set by the hosting platform, not by you.');
    }
    out.push('');
  }

  // --- where to look first ---
  const start = overview.whereToLookFirst.slice(0, MAX_START_FILES);
  if (start.length > 0) {
    out.push('## Where to look first');
    out.push('');
    // The order accounts for *what* imports a file, not just how many things do, and the
    // sentence has to say so — otherwise the count printed beside each line reads as the
    // thing being sorted by, and the first entry looks like a mistake whenever a file
    // that few things import outranks one that many do.
    out.push(
      'The files that pull the most of this app together — entry points, and the modules that wire them up. Ranked by what they depend on, not by how many things touch them.',
    );
    out.push('');
    for (const entry of start) {
      const summary = entry.node.summary ? ` — ${oneLine(entry.node.summary)}${mark(entry.node.summarySource)}` : '';
      const by = `imports ${entry.imports} ${entry.imports === 1 ? 'file' : 'files'}`;
      out.push(`- \`${entry.node.path}\` (${by})${summary}`);
    }
    out.push('');
  }

  out.push('---');
  out.push('');
  out.push(
    'This file is generated. The full atlas — every file, function, type and edge — is in `.app-atlas/atlas.json`, and `app-atlas serve` opens the same information as a map you can click through.',
  );
  out.push('');

  return out.join('\n');
}

/**
 * The "since the last run" section, or the one line that says why there is not one.
 *
 * The first-run line is not filler. A brief that simply omits this section leaves the
 * reader to assume no news is good news, when the truth is that nobody has looked yet —
 * and this file is read by agents, which are exactly the readers most likely to fill a
 * silence with an assumption.
 *
 * Which is why a committed map gets a sentence rather than nothing at all (issue #69).
 * "The last run" means the last run *on this machine*, against a baseline kept in
 * `.app-atlas/`, which is not committed and never leaves it. In a file several people
 * regenerate, that comparison is unanswerable in both directions: a reader has no way to
 * know whose run it was, and whoever regenerates from a fresh checkout has no baseline at
 * all, so an honest "first run" quietly overwrites real information and looks in the diff
 * like an ordinary update. The facts in this file have to be facts every regenerator
 * would produce.
 */
function appendChanges(out: string[], changes: AtlasChanges | undefined, shared: boolean): void {
  if (shared) {
    out.push('## What changed since the last run');
    out.push('');
    out.push(
      'Not recorded here. This file is committed, and what changed since the last run is a comparison against ' +
        'an atlas kept in `.app-atlas/`, which is not — so the answer depends on who ran it and when, and would ' +
        'be wrong for everyone else reading this. Run `app-atlas analyze` to see it for yourself.',
    );
    out.push('');
    return;
  }

  const report = describeChanges(changes);
  if (!report) return;

  out.push('## What changed since the last run');
  out.push('');
  out.push(
    report.tone === 'warn' ? `**${sentenceCase(report.headline.text)}.**` : `${sentenceCase(report.headline.text)}.`,
  );
  appendDoors(out, report.headline.doors);
  for (const line of report.lines) {
    out.push('');
    out.push(`${sentenceCase(line.text)}.`);
    appendDoors(out, line.doors);
  }
  out.push('');
}

/**
 * The ports a deployment file in this repo says it publishes on the host.
 *
 * Its own section, because these are the only doors on the map that no application code
 * opens: there is no handler to read and no auth check to look for, so every other
 * section's vocabulary — method, route, guard — has nothing to say about them.
 *
 * The heading names the *file*, not a server, and so does every line under it. "Port
 * 5432 is open" is a claim about somebody's infrastructure that this tool has no way to
 * check; "compose.yml publishes 5432" is a claim about a file in the repo, which is all
 * that was read. An agent reading this brief must not come away able to tell a customer
 * their database is exposed on the strength of a file nobody may ever run.
 */
function appendPorts(out: string[], graph: AtlasGraph): void {
  const ports = graph
    .nodesOfKind('endpoint')
    .filter((node) => String((node.meta as { endpointKind?: string }).endpointKind) === 'port');
  if (ports.length === 0) return;

  out.push('## Ports a deployment file publishes');
  out.push('');
  out.push(
    'Declared in the files named below, not observed on any machine. Nothing here says the stack is running, ' +
      'and a production deploy may publish something else entirely.',
  );
  out.push('');
  for (const node of ports.slice(0, MAX_PORTS)) {
    const meta = node.meta as { sites?: { path: string; line?: number }[] };
    const site = meta.sites?.[0];
    // The door names its own file, because that is what makes it a claim about a file
    // rather than about a server. Printing the path again after it just reads as noise,
    // so the line number joins the name it already carries.
    const claim = site && node.name.startsWith(`${site.path} `) ? node.name.slice(site.path.length + 1) : node.name;
    const where = site ? `\`${site.path}${site.line ? `:${site.line}` : ''}\` — ` : '';
    out.push(`- ${where}${claim}`);
  }
  if (ports.length > MAX_PORTS) out.push(`- …and ${ports.length - MAX_PORTS} more.`);
  out.push('');
}

/**
 * Tables whose column names suggest they hold personal data (issue #48).
 *
 * The wording carries the whole risk here. This is a name match — no value was ever read
 * — and the sentence a reader takes away in a customer meeting has to survive being wrong
 * in both directions: a column called `address` that holds a wallet, and a column called
 * `payload` that holds a passport number. So the section states its own method up front,
 * separates the direct matches from the ambiguous ones instead of totalling them, and
 * says plainly that a table missing from the list has not been cleared.
 *
 * Written only when something matched. An always-present section here would invite the
 * opposite reading of the one `appendUnimported` needs — "no personal data found" is a
 * claim this method is nowhere near strong enough to make.
 */
function appendPersonalData(out: string[], graph: AtlasGraph): void {
  const report = findPersonalData(graph.allNodes(), graph.allEdges());
  // Nothing matched means no section. The heading promises findings, and printing it over
  // an empty list — nothing but caveats — reads either as a scare or as a clean bill of
  // health, and this method is not strong enough to issue either. The tables whose
  // columns nobody declared are already listed as `columns unknown` directly above.
  if (report.tables.length === 0) return;

  out.push('## Columns whose names suggest personal data');
  out.push('');
  out.push(
    'Matched on column **names** only — App Atlas has not read a single value, and this is not a ' +
      'compliance answer. A name is evidence of what a column was meant to hold, not proof: `address` is a ' +
      'wallet on some apps, and a column called `payload` or `user_reference` can hold a passport number ' +
      'and match nothing here. **A table absent from this list has not been cleared — it has only failed ' +
      'to match a name.**',
  );
  out.push('');

  for (const table of report.tables.slice(0, MAX_PERSONAL_TABLES)) {
    const direct = table.columns.filter((column) => column.strength === 'direct');
    const ambiguous = table.columns.filter((column) => column.strength === 'ambiguous');
    // Every listed table has at least one direct match — that is what earns the row — so
    // the direct clause always leads and the ambiguous one is only ever a suffix. Kept in
    // its own clause, never totalled with the first, because the whole point of the
    // distinction is that one list is worth acting on and the other is worth a glance.
    let shape = direct.map((column) => `\`${column.column}\``).join(', ');
    if (ambiguous.length > 0) {
      shape += `, and, less certainly, ${ambiguous.map((column) => `\`${column.column}\``).join(', ')}`;
    }
    const doors =
      table.doors.length > 0
        ? ` — reached by ${table.doors.slice(0, MAX_REACHING_DOORS).map((door) => `\`${door.name}\``).join(', ')}${
            table.doors.length > MAX_REACHING_DOORS ? ` and ${table.doors.length - MAX_REACHING_DOORS} more` : ''
          }`
        : '';
    out.push(`- **${table.name}** — ${shape}${doors}`);
  }
  if (report.tables.length > MAX_PERSONAL_TABLES) {
    out.push(`- …and ${report.tables.length - MAX_PERSONAL_TABLES} more.`);
  }

  if (report.ambiguousOnly.length > 0) {
    out.push('');
    out.push(
      `${n(report.ambiguousOnly.length)} further ${plural(report.ambiguousOnly.length, 'table', 'tables')} ` +
        `matched only on an ambiguous name such as \`name\` or \`city\`, which is too weak to list as a finding: ` +
        `${report.ambiguousOnly.slice(0, MAX_PERSONAL_TABLES).map((table) => `\`${table.name}\``).join(', ')}` +
        `${report.ambiguousOnly.length > MAX_PERSONAL_TABLES ? ', and others' : ''}.`,
    );
  }

  if (report.unknownColumns.length > 0) {
    out.push('');
    out.push(
      report.unknownColumns.length === 1
        ? 'One more table is named in queries with no schema declaring its columns, so nothing here could ' +
          `look at it either way: \`${report.unknownColumns[0].name}\`.`
        : `${n(report.unknownColumns.length)} more tables are named in queries with no schema declaring their ` +
          'columns, so nothing here could look at them either way: ' +
          `${report.unknownColumns.map((table) => `\`${table.name}\``).join(', ')}.`,
    );
  }
  out.push('');
}

/**
 * The files nothing else in this app imports.
 *
 * The section is written even when the list is empty, and even when the question could
 * not be answered — which is most of the point. This file is read by agents, and an
 * absent section is one an agent fills in with an assumption; "no unused files were
 * found" and "nobody looked for them" are different sentences and would otherwise look
 * identical, which is the same mistake `authHeadline` exists to stop.
 *
 * Nothing here is phrased as an instruction. Every line is a fact about what the import
 * graph does and does not contain, and the caveats that follow are the reason: a file
 * reached by a computed path is invisible to this, permanently, and the wording has to
 * survive being wrong about one.
 */
function appendUnimported(out: string[], view: UnimportedView): void {
  out.push('## Files nothing else imports');
  out.push('');

  if (!view.answered) {
    out.push(`Not reported: ${view.because}.`);
    out.push('');
    return;
  }

  if (view.total === 0) {
    out.push(`${sentenceCase(view.headline ?? '')}.`);
    out.push('');
    return;
  }

  out.push(
    `**${sentenceCase(view.headline ?? '')}** — out of ${n(view.considered)} weighed up. ` +
      'Nothing accounts for them: no import, no door, no manifest entry, no framework convention. ' +
      'Worth opening; not, on this evidence alone, worth deleting.',
  );
  out.push('');
  for (const file of view.files) {
    const names = file.exportedNames.length > 0 ? ` — exports ${file.exportedNames.map((x) => `\`${x}\``).join(', ')}` : '';
    const summary = file.summary ? ` — ${oneLine(file.summary)}${mark(file.summarySource)}` : '';
    out.push(`- \`${file.path}\` (${n(file.loc)} ${plural(file.loc, 'line')}, ${file.zone})${names}${summary}`);
  }
  if (view.total > view.files.length) out.push(`- …and ${view.total - view.files.length} more.`);
  out.push('');
  for (const caveat of view.caveats) out.push(`- ${sentenceCase(caveat)}.`);
  out.push('');
}

/** The doors one sentence is about, named under it, so nobody has to go hunting. */
function appendDoors(out: string[], doors: DoorChange[]): void {
  if (doors.length === 0) return;
  out.push('');
  for (const door of doors.slice(0, MAX_CHANGED_DOORS)) {
    const where = door.path ? ` — \`${door.path}${door.line ? `:${door.line}` : ''}\`` : '';
    out.push(`- \`${door.name}\`${door.writes ? ' — writes data' : ''}${where}`);
  }
  if (doors.length > MAX_CHANGED_DOORS) out.push(`- …and ${doors.length - MAX_CHANGED_DOORS} more.`);
}

/** Marks a sentence a model wrote. The repo's own docstrings need no marking. */
function mark(source: SummarySource): string {
  return source === 'ai' ? ' _(ai)_' : '';
}

/**
 * An unchecked door with a reason reads differently from one without. Printing them
 * identically is what made the old brief's "none found" column something a reader
 * learned to skim past.
 */
function authCell(route: RouteInsight): string {
  const provider = route.guards[0]?.provider ?? route.guards[0]?.name;
  switch (route.open?.kind) {
    case 'worth-a-look':
      return '**none found**';
    case 'unreadable':
      return 'not examined';
    case 'page':
      return 'public page';
    case 'auth-mount':
      return 'the sign-in door';
    default:
      return route.protection === 'likely' ? `${provider ?? 'a check'}?` : (provider ?? 'checked');
  }
}

function sentenceCase(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function oneLine(text: string): string {
  const first = text.split('\n')[0].trim();
  return first.length > 160 ? `${first.slice(0, 159)}…` : first;
}

function percent(part: number, whole: number): string {
  return whole === 0 ? '0%' : `${Math.round((part / whole) * 100)}%`;
}

function n(value: number): string {
  return value.toLocaleString('en-US');
}

function plural(count: number, one: string, many = `${one}s`): string {
  return count === 1 ? one : many;
}
