/**
 * @fileoverview ATLAS.md — the atlas, written for the agent that wrote the app.
 *
 * SPEC.md section 7. An agent starting a session in an unfamiliar repository spends
 * its first several thousand tokens rediscovering the shape of the thing; aider's
 * repo-map proved that handing it the map instead is worth real accuracy. This is that
 * map, in the cheapest form that survives being pasted into a context window.
 *
 * Three rules keep it useful:
 *
 *   - **Facts before prose.** Counts, routes, tables and paths — the things an agent
 *     can act on — come first, and every one of them is compiler-derived.
 *   - **Say what is generated.** A sentence a model wrote is marked `(ai)`. An agent
 *     reading this should weigh its own species' output accordingly.
 *   - **Bounded.** Every list is capped. A map that does not fit in a context window
 *     is not a map, and the atlas itself is one command away for anything deeper.
 */
import type { AtlasGraph } from '../model/graph.js';
import { authHeadline } from '../model/exposure.js';
import { buildInsights } from '../model/insights.js';
import type { RouteInsight } from '../model/insights.js';
import { buildTypeView } from '../model/typeview.js';
import type { SummarySource } from '../model/types.js';

const MAX_ROUTES = 40;
const MAX_PARTS = 14;
const MAX_TYPES = 24;
const MAX_START_FILES = 8;
const MAX_ENV = 30;

/** Doors nobody outside can knock on, so they never appear in the auth table. */
const OTHER_DOORS = new Set(['webhook', 'cron', 'queue', 'cli', 'file-read']);

export interface MarkdownOptions {
  /** Stamped into the header so a stale copy is obvious. Defaults to the atlas's own. */
  generatedAt?: string;
  toolVersion?: string;
}

export function renderAtlasMarkdown(graph: AtlasGraph, options: MarkdownOptions = {}): string {
  const meta = graph.meta;
  const stats = meta.stats;
  const insights = buildInsights(graph);
  const overview = graph.getOverview();
  const out: string[] = [];

  out.push(`# ${meta.name} — map`);
  out.push('');
  out.push(
    `> Generated by App Atlas v${options.toolVersion ?? meta.toolVersion} on ${
      (options.generatedAt ?? meta.generatedAt).slice(0, 10)
    }. Facts are derived by each language's own parser and type checker; sentences marked \`(ai)\` were generated and may be wrong. Re-run \`app-atlas export\` after the code changes.`,
  );
  out.push('');

  const app = overview.app;
  if (app?.summary) {
    out.push(`${app.summary}${mark(app.summarySource)}`);
    out.push('');
  }

  // --- numbers ---
  out.push('## By the numbers');
  out.push('');
  out.push(
    `- ${n(stats.files)} files · ${n(stats.linesOfCode)} lines · ${n(stats.modules)} folders · ${n(stats.functions)} functions · ${n(stats.types)} types`,
  );
  out.push(
    `- ${n(stats.endpoints)} ways in · ${n(stats.externalServices)} outside ${plural(stats.externalServices, 'service')} · ${n(stats.stores)} data ${plural(stats.stores, 'store')} · ${n(stats.envVars)} env vars`,
  );
  if (meta.frameworks.length > 0) out.push(`- Built with ${meta.frameworks.join(', ')}`);
  out.push(
    `- ${percent(stats.documentedFiles, stats.files)} of files carry a docstring App Atlas reads verbatim${
      stats.staleDocs > 0 ? ` · ${stats.staleDocs} describe code that has since changed` : ''
    }`,
  );
  out.push('');

  // --- ways in ---
  if (insights.auth.routes.length > 0) {
    out.push('## Ways in');
    out.push('');
    const auth = authHeadline(stats);
    if (auth) {
      out.push(auth.tone === 'warn' ? `**${sentenceCase(auth.headline)}.** They are listed first.` : `${sentenceCase(auth.headline)}.`);
      for (const caveat of auth.caveats) out.push(`- ${sentenceCase(caveat)}.`);
      out.push('');
    }
    out.push('| Kind | Route | Auth | Writes | Where |');
    out.push('|---|---|---|---|---|');
    for (const route of insights.auth.routes.slice(0, MAX_ROUTES)) {
      out.push(
        `| ${route.method ?? route.endpointKind} | ${route.route ?? route.name} | ${authCell(route)} | ${route.writes ? 'yes' : '—'} | ${route.sites[0]?.path ?? '—'} |`,
      );
    }
    if (insights.auth.routes.length > MAX_ROUTES) {
      out.push(`| … | ${insights.auth.routes.length - MAX_ROUTES} more | | | |`);
    }
    out.push('');
  }

  // Webhooks, crons and workers are not measured for auth coverage — a stranger cannot
  // knock on them — but an agent about to change this code still needs to know they run.
  const others = graph
    .nodesOfKind('endpoint')
    .filter((node) => OTHER_DOORS.has(String((node.meta as { endpointKind?: string }).endpointKind)));
  if (others.length > 0) {
    out.push('## Also runs on its own');
    out.push('');
    for (const node of others) {
      const meta = node.meta as { endpointKind?: string; route?: string; schedule?: string; sites?: { path: string }[] };
      const when = meta.schedule ? ` (${meta.schedule})` : '';
      out.push(`- **${meta.endpointKind}** ${meta.route ?? node.name}${when} — \`${meta.sites?.[0]?.path ?? '—'}\``);
    }
    out.push('');
  }

  // --- where data goes ---
  if (insights.stores.length + insights.services.length > 0) {
    out.push('## Where data goes');
    out.push('');
    for (const store of insights.stores) {
      const tables = store.tables.length > 0 ? ` — tables: ${store.tables.join(', ')}` : '';
      out.push(`- **${store.name}** (${store.client}) — ${store.reads} reads, ${store.writes} writes${tables}`);
    }
    for (const service of insights.services) {
      out.push(
        `- **${service.name}** (${service.category}) — ${service.callSites} call ${service.callSites === 1 ? 'site' : 'sites'}${
          service.evidence.length > 0 ? ` via ${service.evidence.slice(0, 2).join(', ')}` : ''
        }`,
      );
    }
    out.push('');
  }

  // --- the parts ---
  const parts = overview.topLevel.filter((node) => node.kind === 'module').slice(0, MAX_PARTS);
  if (parts.length > 0) {
    out.push('## The parts');
    out.push('');
    for (const part of parts) {
      const files = Number(part.meta.descendantFileCount ?? part.childCount);
      const summary = part.summary ? ` — ${oneLine(part.summary)}${mark(part.summarySource)}` : '';
      out.push(`- \`${part.path || part.name}\` (${files} ${plural(files, 'file')}, ${part.zone})${summary}`);
    }
    out.push('');
  }

  // --- shapes ---
  const types = buildTypeView(graph, MAX_TYPES);
  const tables = types.cards.filter((card) => card.typeKind === 'table');
  const shapes = types.cards.filter((card) => card.typeKind !== 'table');

  if (tables.length > 0) {
    out.push('## Database tables');
    out.push('');
    for (const table of tables) {
      // A table found only by name in a query has no columns to list. Say so, rather
      // than trailing off after the dash as though the row were still being written.
      const columns = table.fields.map((field) => `${field.name}: ${field.type}`).join(', ');
      out.push(`- **${table.name}** — ${columns || 'columns unknown'}`);
    }
    out.push('');
  }

  if (shapes.length > 0) {
    out.push('## Key types');
    out.push('');
    for (const card of shapes) {
      const shape =
        card.fields.length > 0
          ? card.fields.map((field) => `${field.name}${field.optional ? '?' : ''}`).join(', ')
          : (card.aliasOf ?? '');
      out.push(
        `- **${card.name}** (${card.typeKind}, \`${card.path}\`)${card.usage > 0 ? ` — used in ${card.usage} places` : ''}${shape ? ` — ${shape}` : ''}`,
      );
    }
    if (types.total > types.cards.length) {
      out.push(`- …and ${types.total - types.cards.length} more types.`);
    }
    out.push('');
  }

  // --- env ---
  if (insights.env.total > 0) {
    out.push('## Environment variables');
    out.push('');
    const names = insights.env.vars.slice(0, MAX_ENV).map((v) => `\`${v.name}\`${v.documented ? '' : '*'}`);
    out.push(names.join(', ') + (insights.env.total > MAX_ENV ? `, …${insights.env.total - MAX_ENV} more` : ''));
    if (insights.env.undocumented.length > 0) {
      out.push('');
      out.push(
        `\\* not in ${insights.env.exampleFile ?? '.env.example'} — ${insights.env.undocumented.length} of ${insights.env.total} are read by the code but written down nowhere.`,
      );
    }
    out.push('');
  }

  // --- where to look first ---
  const busiest = overview.busiestFiles.slice(0, MAX_START_FILES);
  if (busiest.length > 0) {
    out.push('## Where to look first');
    out.push('');
    out.push('The most connected files, which is usually where the app actually lives.');
    out.push('');
    for (const entry of busiest) {
      const summary = entry.node.summary ? ` — ${oneLine(entry.node.summary)}${mark(entry.node.summarySource)}` : '';
      out.push(`- \`${entry.node.path}\` (${entry.connections} connections)${summary}`);
    }
    out.push('');
  }

  out.push('---');
  out.push('');
  out.push(
    'This file is generated. The full atlas — every file, function, type and edge — is in `.app-atlas/atlas.json`, and `app-atlas serve` opens the same information as a map you can click through.',
  );
  out.push('');

  return out.join('\n');
}

/** Marks a sentence a model wrote. The repo's own docstrings need no marking. */
function mark(source: SummarySource): string {
  return source === 'ai' ? ' _(ai)_' : '';
}

/**
 * An unchecked door with a reason reads differently from one without. Printing them
 * identically is what made the old brief's "none found" column something a reader
 * learned to skim past.
 */
function authCell(route: RouteInsight): string {
  const provider = route.guards[0]?.provider ?? route.guards[0]?.name;
  switch (route.open?.kind) {
    case 'worth-a-look':
      return '**none found**';
    case 'unreadable':
      return 'not examined';
    case 'page':
      return 'public page';
    case 'auth-mount':
      return 'the sign-in door';
    default:
      return route.protection === 'likely' ? `${provider ?? 'a check'}?` : (provider ?? 'checked');
  }
}

function sentenceCase(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function oneLine(text: string): string {
  const first = text.split('\n')[0].trim();
  return first.length > 160 ? `${first.slice(0, 159)}…` : first;
}

function percent(part: number, whole: number): string {
  return whole === 0 ? '0%' : `${Math.round((part / whole) * 100)}%`;
}

function n(value: number): string {
  return value.toLocaleString('en-US');
}

function plural(count: number, one: string, many = `${one}s`): string {
  return count === 1 ? one : many;
}
