// Code generated by protoc-gen-go. DO NOT EDIT.

package store

// OrderProto is machine-written and nobody reads it.
type OrderProto struct {
	Id     string
	Status string
}

// Reset implements the proto.Message contract.
func (m *OrderProto) Reset() {}
